### ISSUE TITLE
Issue with webpack loader

### ISSUE THREAD

**Issue by divyeshpu** [BosNaufal/react-loading-bar#1]
Module parse failed: react-loadingbar/src/js/components/index.js Unexpected token (37:6)
You may need an appropriate loader to handle this file type.

do we need some js loader for this module

**Comment by BosNaufal** [comment]
@nabster11 have you do `npm install`?

**Comment by divyeshpu** [comment]
yup i did that..still i get that error.

**Comment by BosNaufal** [comment]
Hey @nabster11, I've just patch the npm package, You can try it now~

**Comment by BosNaufal** [comment]
@nabster11 I think, it should no problem when you have installed the devDependencies of React Loading Bar. Since it need babel loader (react presets & es2015) and sass-loader (with node-sass). Do you have those package in your project?
